export const products = [
  {
    id: 1,
    name: "Sony WH-1000XM5 Wireless Headphones",
    category: "Electronics",
    price: 29990,
    rating: 4.8,
    reviews: 1245,
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=600&q=80",
    isNew: true,
    description: "Industry-leading noise cancellation with Auto NC Optimizer. Up to 30-hour battery life with quick charging (3 min charge for 3 hours of playback). Premium comfort with soft fit leather.",
  },
  {
    id: 2,
    name: "Apple MacBook Air M2",
    category: "Electronics",
    price: 114900,
    rating: 4.9,
    reviews: 840,
    image: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=600&q=80",
    isNew: false,
    description: "Strikingly thin design with the incredibly fast M2 chip. Features a beautiful 13.6-inch Liquid Retina display, 1080p FaceTime HD camera, and up to 18 hours of battery life.",
  },
  {
    id: 3,
    name: "Nike Air Force 1 '07",
    category: "Clothing",
    price: 8500,
    rating: 4.7,
    reviews: 3200,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80",
    isNew: false,
    description: "The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold colors, and the perfect amount of flash.",
  },
  {
    id: 4,
    name: "Minimalist Leather Backpack",
    category: "Accessories",
    price: 4500,
    rating: 4.5,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
    isNew: true,
    description: "Handcrafted from premium full-grain leather, this minimalist backpack features a padded laptop sleeve, water-resistant interior, and ergonomic shoulder straps for daily commuting.",
  },
  {
    id: 5,
    name: "Samsung Galaxy Watch 5 Pro",
    category: "Electronics",
    price: 34999,
    rating: 4.6,
    reviews: 512,
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=600&q=80",
    isNew: false,
    description: "Advanced sleep tracking, improved health sensors, and a tougher sapphire crystal glass display. The Galaxy Watch 5 Pro is built for adventurers with GPS tracking and an extended battery.",
  },
  {
    id: 6,
    name: "Patagonia Classic Fleece",
    category: "Clothing",
    price: 9500,
    rating: 4.8,
    reviews: 890,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80",
    isNew: false,
    description: "A warm, versatile quarter-zip pullover made of 100% recycled polyester fleece. Fair Trade Certified™ sewn, meaning the people who made it earned a premium for their labor.",
  },
  {
    id: 7,
    name: "Hydro Flask 32 oz Wide Mouth",
    category: "Accessories",
    price: 3500,
    rating: 4.9,
    reviews: 2100,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    isNew: false,
    description: "Keep cold drinks icy cold and hot drinks piping hot for hours. TempShield™ double wall vacuum insulation protects temperature, while the Color Last™ powder coat is slip-free.",
  },
  {
    id: 8,
    name: "Logitech MX Master 3S",
    category: "Electronics",
    price: 8995,
    rating: 4.8,
    reviews: 1450,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80",
    isNew: false,
    description: "An iconic mouse remastered for ultimate tactility, performance, and flow. Features Quiet Clicks, an 8000 DPI track-on-glass sensor, and the remarkable MagSpeed electromagnetic wheel.",
  },
  {
    id: 9,
    name: "Ray-Ban Classic Aviator",
    category: "Accessories",
    price: 10500,
    rating: 4.6,
    reviews: 430,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
    isNew: false,
    description: "Originally designed for U.S. aviators in 1937, Ray-Ban Aviator Classic sunglasses are a timeless model that combines great aviator styling with exceptional quality, performance and comfort.",
  },
  {
    id: 10,
    name: "Levis 501 Original Fit Jeans",
    category: "Clothing",
    price: 4200,
    rating: 4.5,
    reviews: 1100,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=600&q=80",
    isNew: false,
    description: "The original blue jean since 1873. The original straight fit with signature button fly. A cultural icon, worn by generations, defining style for decades.",
  },
  {
    id: 11,
    name: "Kindle Paperwhite",
    category: "Electronics",
    price: 13999,
    rating: 4.8,
    reviews: 5600,
    image: "https://images.unsplash.com/photo-1592496001020-d31bd830651f?auto=format&fit=crop&w=600&q=80",
    isNew: true,
    description: "Now with a 6.8\" display and thinner borders, adjustable warm light, up to 10 weeks of battery life, and 20% faster page turns. Waterproof for reading by the pool or in the bath.",
  },
  {
    id: 12,
    name: "Fossil Gen 6 Smartwatch",
    category: "Accessories",
    price: 18500,
    rating: 4.3,
    reviews: 320,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
    isNew: false,
    description: "Powered with Wear OS by Google. Faster performance, lower power consumption, and blood oxygen tracking. Track activity, monitor heart rate, and receive smartphone notifications.",
  }
];
